### ISSUE TITLE
Scalable Webhook pattern is missing step 3 within the interactive reference architecture

### ISSUE THREAD

**Issue by ryanycoleman** [jeremydaly/reference-architectures#1]
Hello @jeremydaly! The Serverless Reference Architectures Project is great! Thanks for sharing and making this repo accessible for contributions. 

I noticed that step 3 is missing from the [scalable webhook pattern](https://www.jeremydaly.com/the-scalable-webhook/) and didn't see a way to address it here so thought I'd let you know via Issues. I visited via Edge browser, v83.0.478.56.

**Comment by jeremydaly** [comment]
FIXED! Thanks for letting me know.
